from src.constants.config_const import *

MS_TEN_S = 10_000

WIKI_PAGES = [
    'Assassination Classroom Henshū', 
    'Black Clover Kaï', 
    'Black Lagoon Henshū', 
    'Bleach Kaï (Mixouille)', 
    'Bleach Yabai (Johker)', 
    'Blue Lock Henshū', 
    'Boruto Kai', 
    'Busô Renkin Kaï', 
    'Call of the Night Henshū', 
    'Chainsaw Man Henshū', 
    'D.Gray-man Kaï', 
    'Death Note Kaï', 
    'Demon Slayer Henshū', 
    'Détective Conan Kaï', 
    'Dr.Stone Henshū', 
    'Dragon Ball Yabai', 
    'Dragon Ball Z Yabai / Dragon Ball Z Kai', 
    'Dragon Ball GT FAN/CUT', 
    'Dragon Ball Super Kaï', 
    'Enfer et Paradis Henshū', 
    'Fairy Tail Kaï', 
    'Fire Force Henshū', 
    # 'Food Wars Kaï', 
    'Frieren Henshū',
    'Fullmetal Alchemist Kaï', 
    'Gintama Kaï', 
    'Haikyuu!! Henshū', 
    'Hajime no Ippo Henshū', 
    'Hikaru no Go Henshū', 
    'Hokuto no Ken Kaï', 
    'Horimiya Kaï', 
    'Hunter x Hunter (1999) Kaï', 
    'Hunter x Hunter (2011) Kaï', 
    'Inazuma Eleven FAN/CUT', 
    'Initial D Kaï', 
    'Inuyashiki Last Hero Henshū',
    "Jojo's Bizarre Adventure Henshū",
    'Jujutsu Kaisen Henshū', 
    'Kaguya-sama : Love is War Henshū', 
    'Kuroko no Basket Henshū',
    'L\'attaque des Titans Henshū', 
    'Lastman FAN/CUT', 
    'Made in Abyss Henshū', 
    'Mirai Nikki Henshū', 
    'Monster Kaï',
    'Monster Henshū',
    'My Hero Academia Henshū', 
    'Naruto Shippuden Kaï (Mixouille)', 
    'Naruto Yabai (Triggerforce)', 
    'Naruto Shippuden Yabai (Triggerforce)', 
    'Neon Genesis Evangelion FAN/CUT', 
    'Nichijou Henshū', 
    'One Piece Kaï Ultime Pack', 
    'One Piece Yabai', 
    'One Piece Kaï', 
    'One Punch Man Henshū', 
    'Oshi no Ko Henshū', 
    'Overlord Henshū', 
    'Parasyte - the maxim Henshū', 
    'Radiant Kaï', 
    'Reborn! Kaï', 
    'Record of Ragnarök Henshū', 
    'Re:Zero Kaï', 
    'Saint Seiya Kaï', 
    'Seven Deadly Sins Henshū', 
    'Shingeki no Kyojin Henshū', 
    'Shiki Henshū', 
    'Slam Dunk Kaï', 
    'Solo Leveling Henshū', 
    'Soul Eater Kaï', 
    'Spy x Family Henshū', 
    'Street Fighter II V FAN/CUT', 
    'Sword Art Online Kaï', 
    'Tokyo Revengers Henshū', 
    'To Your Eternity Henshū', 
    'Tower of God Henshū', 
    'Vinland Saga Henshū', 
    'World Trigger Kaï', 
    'Yu Yu Hakusho Kaï',
]